pip install --user BeautifulSoup
pip install --user Misago
pip install --user MySQLdb
pip install --user OpenSSL
pip install --user Orange
pip install --user Pillow
pip install --user deepwalk
pip install --user django
pip install --user email
pip install --user gensim
pip install --user gym
pip install --user jieba
pip install --user keras
pip install --user lxml
pip install --user mysql
pip install --user networkx
pip install --user nltk
pip install --user numpy
pip install --user pip
pip install --user pybrain
pip install --user pymongo
pip install --user pysql
pip install --user pysqlite2
pip install --user scrapy
pip install --user six
pip install --user sklearn
pip install --user snap
pip install --user theano
pip install --user urllib3
pip install --user word2vec
pip install --user flask
pip install --user keras
pip install --user nltk
pip install --user notebook
pip install --user numpy
pip install --user pandas
pip install --user pyltp
pip install --user scipy
pip install --user seaborn
pip install --user tensorflow
pip install --user tensorlayer
pip install --user zhihu_oauth
